name: Duel
version: 1.0.0
author: mogu
main: com.DuelPlugin
api-version: 1.16

commands:
  duel:
    description: Duel another player!
    usage: /duel [player]
    aliases: [du]

  duelaccept:
    description: Accept another player's duel.
    usage: /duelaccept
    aliases: [da]

  adddb:
    description: "[DEBUG] Add a row to the database."
    usage: /duel [player]
    aliases: [du]

  leaderboard:
    description: "[DEBUG] Display duel leaderboards."
    usage: /leaderboard
    aliases: [lb]

  saveinv:
    description: "[DEBUG] Save and restore player inventory."
    usage: /saveinv
    aliases: [si]
